require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: "brackets"

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 10


RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExpectChange:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
